-- CREATE TABLE NEWBOOK (
-- 	BOOKNAME VARCHAR(20) NOT NULL,
--     PUBLISHER VARCHAR(20) UNIQUE,
--     PRICE INT DEFAULT 10000 CHECK(PRICE > 2000),
--     PRIMARY KEY (BOOKNAME, PUBLISHER)
-- );

-- CREATE TABLE NEWCUSTOMER (
-- 	CUSTID INT PRIMARY KEY,
--     NAME VARCHAR(40),
--     ADDRESS VARCHAR(40),
--     PHONE VARCHAR(30)
-- );

-- CREATE TABLE NEWORDERS (
-- 	ORDERID INT,
--     CUSTID INT NOT NULL,
--     BOOKID INT NOT NULL,
--     SALEPRICE INT,
--     ORDERDATE DATE,
--     PRIMARY KEY (ORDERID),
--     FOREIGN KEY (CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE
-- );

-- INSERT INTO NEWBOOK (`BOOKNAME`,`PUBLISHER`,`PRICE`) VALUES ('어린왕자','조나단',10000);
-- INSERT INTO NEWBOOK (`BOOKNAME`,`PUBLISHER`,`PRICE`) VALUES ('개미','헝그리',10000);

-- INSERT INTO NEWCUSTOMER (`CUSTID`,`NAME`,`ADDRESS`,`PHONE`) VALUES (1, '김연아', '서울', '010-1111-1111');
-- INSERT INTO NEWCUSTOMER (`CUSTID`,`NAME`,`ADDRESS`,`PHONE`) VALUES (2, '박지성', '안양', '010-2222-2222');

-- INSERT INTO neworders (`ORDERID`,`CUSTID`,`BOOKID`,`SALEPRICE`,`ORDERDATE`) VALUES (1, '1', '1', 8000, '2022-03-23');
-- INSERT INTO neworders (`ORDERID`,`CUSTID`,`BOOKID`,`SALEPRICE`,`ORDERDATE`) VALUES (2, 1, 2, 5000, '2024-11-01');

-- 

-- NEWBOOK테이블에 ISBN 속성을 VARCHAR(13) 자료형으로 추가하기
-- ALTER TABLE NEWBOOK
-- ADD ISBN VARCHAR(13);

-- NEWBOOK 테이블의 ISBN 속성의 데이터 타입을 INT형으로 변경하기
-- ALTER TABLE NEWBOOK
-- MODIFY ISBN INT;

-- NEWBOOK 테이블의 ISBN 속성을 삭제하기
-- ALTER TABLE NEWBOOK
-- DROP COLUMN ISBN

-- NEWBOOK 테이블의 NUMBER 자료형을 가진 BOOKID 속성 추가하기
-- ALTER TABLE NEWBOOK
-- ADD BOOKID INT;

-- NEWBOOK 테이블의 BOOKID 속성에 NOT NULL 제약조건을 적용하기
-- Step 1: NULL 값을 특정 기본 값으로 업데이트
-- UPDATE NEWBOOK
-- SET BOOKID = 0
-- WHERE BOOKID IS NULL;

-- -- Step 2: NOT NULL 제약 조건 추가
-- ALTER TABLE NEWBOOK
-- MODIFY BOOKID INT NOT NULL;

-- NEWBOOK 테이블의 BOOKID 속성을 기본키로 변경하기

-- Step 1: 기존 기본 키 삭제
-- ALTER TABLE NEWBOOK
-- DROP PRIMARY KEY;

-- Step 1: 기존 BOOKID 열을 삭제하고 다시 추가
-- ALTER TABLE NEWBOOK
-- DROP COLUMN BOOKID;

-- Step 2: BOOKID 열을 AUTO_INCREMENT와 PRIMARY KEY로 추가
-- ALTER TABLE NEWBOOK
-- ADD BOOKID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- (선택 사항) Step 3: AUTO_INCREMENT 속성을 제거하고 BOOKID만 기본 키로 유지
-- ALTER TABLE NEWBOOK
-- MODIFY COLUMN BOOKID INT NOT NULL;


