-- DROP TABLE DEPT_TCL;

-- CREATE TABLE DEPT_TCL
-- AS SELECT * FROM DEPT;

-- INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
-- UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
-- DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

-- ROLLBACK;

-- INSERT INTO DEPT_TCL VALUES(50, "NETWORK", 'SEOUL');
-- UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;
-- DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

-- COMMIT

-- SELECT * FROM DEPT_TCL;

# DELETE는 COMMIT을 해야 DB에 완전히 저장된다.
-- DELETE FROM DEPT_TCL
-- WHERE DEPTNO = 50;
-- SELECT * FROM DEPT_TCL;

-- COMMIT

# UPDATE는 COMMIT을 해야 DB에 완전히 저장된다.
-- UPDATE DEPT_TCL SET LOC='SEOUL'
-- WHERE DEPTNO = 30;
-- SELECT * FROM DEPT_TCL;
## 커밋을 할 때까지 SESSION2에서 대기함.
-- COMMIT